import { createHash } from "node:crypto";
import type { BlockIssue, ManagedBlock } from "./types.ts";

/**
 * Managed blocks (decisions D4, D7, D9):
 *
 *     <!-- agent-rules:begin source=<pack-id> rev=<git sha> hash=<sha256 of body> -->
 *     ...
 *     <!-- agent-rules:end -->
 *
 * Markers occupy a whole line. `source` and `hash` are required, `rev` is optional, other
 * `key=value` attributes are ignored. Blocks do not nest; a second `begin` before an `end`, an
 * `end` without a `begin`, or a `begin` without an `end` is reported as a malformed marker and the
 * enclosing text is not treated as a block.
 */

const BEGIN = /^\s*<!--\s*agent-rules:begin\b([^>]*?)-->\s*$/;
const END = /^\s*<!--\s*agent-rules:end\s*-->\s*$/;
const ANY_MARKER = /^\s*<!--\s*agent-rules:/;
const ATTRIBUTE = /([A-Za-z][A-Za-z0-9_-]*)=("[^"]*"|'[^']*'|\S+)/g;

/**
 * Hash of a block body, the value written to `hash=`.
 *
 * Line endings are normalized to `\n` and surrounding blank lines are dropped before hashing, so
 * a checkout with `autocrlf` or an editor that adds a final newline does not turn a distributed
 * block into a `modified` one (D9).
 */
export function hashBlockBody(body: string): string {
  return createHash("sha256").update(normalizeBody(body)).digest("hex");
}

export function normalizeBody(body: string): string {
  return body.replace(/\r\n/g, "\n").trim();
}

export interface ParsedBlocks {
  readonly blocks: ReadonlyArray<ManagedBlock>;
  readonly issues: ReadonlyArray<BlockIssue>;
}

function parseAttributes(text: string): Map<string, string> {
  const attributes = new Map<string, string>();
  for (const match of text.matchAll(ATTRIBUTE)) {
    const key = match[1] ?? "";
    let value = match[2] ?? "";
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    attributes.set(key, value);
  }
  return attributes;
}

interface OpenBlock {
  readonly line: number;
  readonly source: string;
  readonly hash: string;
  readonly rev: string | null;
}

/** Find every managed block in `content`. `file` is only carried into the results. */
export function parseBlocks(file: string, content: string): ParsedBlocks {
  const blocks: ManagedBlock[] = [];
  const issues: BlockIssue[] = [];
  const malformed = (line: number, message: string) =>
    issues.push({ kind: "malformed-marker", file, line, message });

  const lines = content.split("\n");
  let open: OpenBlock | null = null;

  for (let index = 0; index < lines.length; index += 1) {
    const rawLine = lines[index] ?? "";
    const lineNumber = index + 1;

    const begin = BEGIN.exec(rawLine);
    if (begin) {
      if (open) {
        malformed(
          lineNumber,
          `\`agent-rules:begin\` inside the block opened at line ${open.line}; blocks do not nest`,
        );
        open = null;
      }
      const attributes = parseAttributes(begin[1] ?? "");
      const source = attributes.get("source");
      const hash = attributes.get("hash");
      if (!source || !hash) {
        malformed(lineNumber, `\`agent-rules:begin\` is missing ${source ? "hash=" : "source="}`);
        continue;
      }
      open = { line: lineNumber, source, hash, rev: attributes.get("rev") ?? null };
      continue;
    }

    if (END.test(rawLine)) {
      if (!open) {
        malformed(lineNumber, "`agent-rules:end` without a matching `agent-rules:begin`");
        continue;
      }
      const body = lines.slice(open.line, index).join("\n");
      const bodyHash = hashBlockBody(body);
      blocks.push({
        file,
        source: open.source,
        rev: open.rev,
        hash: open.hash,
        bodyHash,
        line: open.line,
        endLine: lineNumber,
        body,
        modified: open.hash !== bodyHash,
      });
      open = null;
      continue;
    }

    if (ANY_MARKER.test(rawLine) && rawLine.includes("-->")) {
      malformed(lineNumber, `unrecognized \`agent-rules:\` marker: ${rawLine.trim()}`);
    }
  }

  if (open) malformed(open.line, "`agent-rules:begin` without a matching `agent-rules:end`");

  return { blocks, issues };
}

/**
 * A single-line HTML comment that another generator uses to mark a region it owns, or to mark
 * the whole file as generated. Inserting a block into such a file needs a human first.
 *
 * Recognized: a comment containing `managed`, `generated`, `autogenerated`, or `do not edit`
 * (any case), or a region marker starting with `BEGIN` / `END` in capitals
 * (`<!-- BEGIN_TF_DOCS -->`, `<!-- END: foo -->`). Our own `agent-rules:` markers are not foreign.
 */
const SINGLE_LINE_COMMENT = /^\s*<!--[^>]*-->\s*$/;
const FOREIGN_WORDS = /\b(?:managed|generated|autogenerated|do not edit)\b/i;
const FOREIGN_REGION = /^\s*<!--\s*(?:BEGIN|END)(?![a-z])/;

export function findForeignMarkers(file: string, content: string): BlockIssue[] {
  const issues: BlockIssue[] = [];
  content.split("\n").forEach((rawLine, index) => {
    if (ANY_MARKER.test(rawLine) || !SINGLE_LINE_COMMENT.test(rawLine)) return;
    if (!FOREIGN_WORDS.test(rawLine) && !FOREIGN_REGION.test(rawLine)) return;
    issues.push({
      kind: "foreign-marker",
      file,
      line: index + 1,
      message: `another tool marks this file: ${rawLine.trim()}`,
    });
  });
  return issues;
}
